config/routes.rb
SampleApp::Application.routes.draw do
  
  get '/users/:id/activate/:password_reset_token' => 'users#activate', as: :user_activate

  resources :password_resets
  
  resources :users  do
    member do
      get :followers, :following
    end
  end
  resources :sessions, only: [:create, :destroy, :new]
  resources :microposts, only: [:index, :create, :destroy]
  resources :messages,  only: [:create, :destroy, :index]
  resources :relationships, only: [:create, :destroy]

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  
  root 'static_pages#home'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/shared/_delete_micropost.html.erb
<% if current_user?(object.user) %>
	<%= link_to "delete", object, method: :delete, data: { confirm: "You sure?" }, title: object.content %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			This form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<% object.errors.full_messages.each do |m| %>
				<li>* <%= m %></li>
			<% end %>
		</ul>
	</div>

<% end %>

app/views/shared/_feed.html.erb
<h3>Micropost Feed</h3>
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user">
		<%= link_to feed_item.user.name, feed_item.user %>
	</span>
	<span class="content">
		<%= wrap(feed_item.content) %>
	</span>
	<span class="timestamp">
		Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
	</span>
	<%= render 'shared/delete_micropost', object: feed_item %>
	<% unless current_user?(feed_item.user) %>
		<a class="reply" data-username="<%= feed_item.user.username %>" >reply</a> 
	<% end %>
</li>

app/views/shared/_home_non_signed_in.html.erb
<div class="center hero-unit">
  <h1>Welcome to Chirrups.</h1>

  <h2>
    Start a conversation, explore your interests.
  </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>

<p>Hi and welcome to Chirrups. This is basically a website built upon the resulting application from following Michael Hartl's tutorial at http://railstutorial.org/book.</p>

<h3>What's been added?</h3>
<p>On chapter 12 of the said tutorial, Mike listed possible extensions to the application, which a follower can work on. He said, "implementing one or more of these application extensions will help you make the transition from following a tutorial to writing original applications of your own."</p>

<p>Here's what's been added so far. I'm currently working on the last three extensions.

<ul class="list-group">
	<li class="list-group-item">Replies</li>
	<li class="list-group-item">Messaging</li>
	<li class="list-group-item">Follower notifications</li>
	<li class="list-group-item">Password reminders</li>
	<li class="list-group-item">Signup confirmation</li>
</ul>
</p>
<h3>Show me the codes!</h3>
<p>If you came here to see how far this application has gone from the original version, please visit <br/> <a href="https://github.com/abhay-github/sample_app4/compare/original-version...master" class="btn btn-danger btn-large">here</a> </p>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/shared/_home_signed_in.html.erb
<%= javascript_include_tag("microposts.js") %>
<div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
      <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="span8">

      <div class="btn-group" data-toggle="buttons-radio">
        <button id="showMcrpst" type="button" class="btn btn-large <%= @viewMsgs ? '' : 'active' %>">Microposts</button>
        <button id="showMsg" type="button" class="btn btn-large  <%= @viewMsgs ? 'active' : '' %>">Messages</button>
      </div>

      <div class="home_content">
        <% if @viewMsgs %>
          <%= render 'messages/index' %>
        <% else %>
          <%= render 'shared/feed' %>
        <% end %>
      </div>
      
    </div>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
	<%= render 'shared/error_messages', object: @msg || @micropost %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost / message ....", maxlength: 140 %>
	</div>
	<%= f.submit "Post", class: "btn btn-primary btn-large" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.followed_users.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>	
</div>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
	<%= gravatar_for current_user, size: 52 %>
</a>
<h1><%= current_user.name %></h1>
<span class="obscure">@<%= current_user.username %></span>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize current_user.microposts.count, "micropost" %></span>